<?php
$imgDomain = include(dirname(__FILE__).'/../../protected/config/main.php');
$imgDomain = empty($imgDomain['params']['imgDomain']) ? '' : substr($imgDomain['params']['imgDomain'],0,-1);
$imgDomain = $imgDomain ? $imgDomain : (empty($_SERVER['SERVER_NAME'])?(empty($_SERVER['HTTP_HOST'])?'':$_SERVER['HTTP_HOST']):$_SERVER['SERVER_NAME']);

return array
(
	'imageActionName'			=> 'uploadimage',
	'imageFieldName'			=> 'upfile',
	'imageMaxSize'				=> 5242880,
	'imageAllowFiles'			=> array('.png', '.jpg', '.jpeg', '.gif', '.bmp'),
	'imageCompressEnable'		=> true,
	'imageCompressBorder'		=> 1600,
	'imageInsertAlign'			=> 'none',
	'imageUrlPrefix'			=> $imgDomain,
	'imagePathFormat'			=> '/DUeditor/photo/{yyyy}/{mm}-{dd}/{rand:8}_{time}',
	'scrawlActionName'			=> 'uploadscrawl',
	'scrawlFieldName'			=> 'upfile',
	'scrawlAllowFiles'			=> '',
	'scrawlPathFormat'			=> '/DUeditor/scrawl/{yyyy}/{mm}-{dd}/{rand:8}.{time}',
	'scrawlMaxSize'				=> 2048000,
	'scrawlUrlPrefix'			=> $imgDomain,
	'scrawlInsertAlign'			=> 'none',
	'snapscreenActionName'		=> 'uploadimage',
	'snapscreenPathFormat'		=> '/DUeditor/snapscreen/{yyyy}/{mm}-{dd}/{rand:7}_{time}',
	'snapscreenUrlPrefix'		=> $imgDomain,
	'snapscreenInsertAlign'		=> 'none',
	'catcherLocalDomain'		=> array('127.0.0.1', 'localhost'),
	'catcherActionName'			=> 'catchimage',
	'catcherFieldName'			=> 'source',
	'catcherPathFormat'			=> '/DUeditor/catcher/{yyyy}/{mm}-{dd}/{rand:7}.{time}',
	'catcherUrlPrefix'			=> $imgDomain,
	'catcherMaxSize'			=> 2048000,
	'catcherAllowFiles'			=> array('.png', '.jpg', '.jpeg', '.gif', '.bmp'),
	'videoActionName'			=> 'uploadvideo',
	'videoFieldName'			=> 'upfile',
	'videoPathFormat'			=> '/DUeditor/video/{yyyy}/{mm}-{dd}/{rand:8}_{time}',
	'videoUrlPrefix'			=> $imgDomain,
	'videoMaxSize'				=> 102400000,
	'videoAllowFiles'			=> array('.flv', '.swf', '.mkv', '.avi', '.rm', '.rmvb', '.mpeg', '.mpg', '.ogg', '.ogv', '.mov', '.wmv', '.mp4', '.webm', '.mp3', '.wav', '.mid'),
	'fileActionName'			=> 'uploadfile',
	'fileFieldName'				=> 'upfile',
	'filePathFormat'			=> '/DUeditor/files/{yyyy}/{mm}-{dd}/{rand:8}_{time}',
	'fileUrlPrefix'				=> $imgDomain,
	'fileMaxSize'				=> 51200000,
	'fileAllowFiles'			=> array('.png', '.jpg', '.jpeg', '.gif', '.bmp', '.flv', '.swf', '.mkv', '.avi', '.rm', '.rmvb', '.mpeg', '.mpg', '.ogg', '.ogv', '.mov', '.wmv', '.mp4', '.webm', '.mp3', '.wav', '.mid', '.rar', '.zip', '.tar', '.gz', '.7z', '.bz2', '.cab', '.iso', '.doc', '.docx', '.xls', '.xlsx', '.ppt', '.pptx', '.pdf', '.txt', '.md', '.xml'),
	'imageManagerActionName'	=> 'listimage',
	'imageManagerListPath'		=> '/DUeditor/photo/',
	'imageManagerListSize'		=> 20,
	'imageManagerUrlPrefix'		=> $imgDomain,
	'imageManagerInsertAlign'	=> 'none',
	'imageManagerAllowFiles'	=> array('.png', '.jpg', '.jpeg', '.gif', '.bmp'),
	'fileManagerActionName'		=> 'listfile',
	'fileManagerListPath'		=> '/DUeditor/files/',
	'fileManagerUrlPrefix'		=> $imgDomain,
	'fileManagerListSize'		=> 20,
	'fileManagerAllowFiles'		=> array('.png', '.jpg', '.jpeg', '.gif', '.bmp', '.flv', '.swf', '.mkv', '.avi', '.rm', '.rmvb', '.mpeg', '.mpg', '.ogg', '.ogv', '.mov', '.wmv', '.mp4', '.webm', '.mp3', '.wav', '.mid', '.rar', '.zip', '.tar', '.gz', '.7z', '.bz2', '.cab', '.iso', '.doc', '.docx', '.xls', '.xlsx', '.ppt', '.pptx', '.pdf', '.txt', '.md', '.xml')
);